const employees = [
  {
    id: 1,
    name: "Shourya",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Web Development",
        category: "Development",
        taskDate: "2025-02-04",
        description: "Build a landing page using React.js and Tailwind CSS.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "UI/UX Design",
        category: "Design",
        taskDate: "2025-02-06",
        description: "Create wireframes and UI designs for the mobile app.",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "API Integration",
        category: "Development",
        taskDate: "2025-02-07",
        description: "Integrate third-party APIs for payment processing.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    name: "Amitabh",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Database Optimization",
        category: "Database Management",
        taskDate: "2025-02-03",
        description: "Optimize database queries for faster performance.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Data Backup",
        category: "Database Management",
        taskDate: "2025-02-08",
        description: "Set up automated backups for critical data.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Database Security Audit",
        category: "Security",
        taskDate: "2025-02-10",
        description: "Analyze and secure the database against SQL injections.",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Indexing Strategy",
        category: "Database Management",
        taskDate: "2025-02-12",
        description: "Develop an indexing strategy for faster queries.",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    name: "Deepika",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Cybersecurity Audit",
        category: "Security",
        taskDate: "2025-02-05",
        description: "Perform security testing on the web application.",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Penetration Testing",
        category: "Security",
        taskDate: "2025-02-09",
        description: "Simulate cyberattacks to test application defenses.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Encryption Standards Update",
        category: "Security",
        taskDate: "2025-02-11",
        description: "Update encryption algorithms to the latest standards.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    name: "Ranbir",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Graphic Design",
        category: "Design",
        taskDate: "2025-02-07",
        description: "Create social media graphics and banners.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Product Branding",
        category: "Design",
        taskDate: "2025-02-08",
        description: "Develop a branding guide for a new product line.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Logo Redesign",
        category: "Design",
        taskDate: "2025-02-10",
        description: "Revamp the company logo for a modern look.",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Ad Campaign Design",
        category: "Marketing",
        taskDate: "2025-02-12",
        description: "Design digital ads for an upcoming campaign.",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    name: "Priyanka",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Content Writing",
        category: "Marketing",
        taskDate: "2025-02-08",
        description: "Write blog posts about AI and technology trends.",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "SEO Optimization",
        category: "Marketing",
        taskDate: "2025-02-09",
        description: "Improve website SEO rankings with better keywords.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Social Media Strategy",
        category: "Marketing",
        taskDate: "2025-02-11",
        description: "Develop an engagement strategy for social platforms.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Newsletter Campaign",
        category: "Marketing",
        taskDate: "2025-02-13",
        description: "Write and design monthly newsletters.",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    name : "Admin",
    email: "admin@gmail.com",
    password: "123",
  },
];
export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));

  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
